version: '3'
services:
    api:
        container_name: api-users
        image: williancarlos/crus-user-helpper:v1
        ports: 
            - 5000:5000  
        environment: 
            POSTGRES_URL : postgres://admin:12345@postgres/usuarios
            KEY: myKeySecrect
            SALT_PWD: 3 
        
        depends_on: 
            - postgres 
        #command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "npm", "test", "mocha --timeout 10000 --exit ./testes/Test*.js"]
        command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "npm", "start", "Api.js"]
       

        links: 
            - postgres

    postgres:
        container_name: "psql"
        image: postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: 
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: usuarios 
            
       